// <auto-generated />
using System;
using GestionPersonnelMairie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionPersonnelMairie.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("GestionPersonnelMairie.Models.Agent", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Adresse").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("DateEmbauche").HasColumnType("TEXT");
                    b.Property<DateTime?>("DateNaissance").HasColumnType("TEXT");
                    b.Property<string>("Departement").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("IdPoste").HasColumnType("INTEGER");
                    b.Property<int>("IdService").HasColumnType("INTEGER");
                    b.Property<string>("Nom").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PhotoUrl").HasColumnType("TEXT");
                    b.Property<string>("Prenom").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal>("Salaire").HasColumnType("TEXT");
                    b.Property<string>("Sexe").HasColumnType("TEXT");
                    b.Property<int>("SoldeCongeAnnuel").HasColumnType("INTEGER");
                    b.Property<int>("SoldeCongeRestant").HasColumnType("INTEGER");
                    b.Property<string>("Statut").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Telephone").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("IdPoste");
                    b.HasIndex("IdService");
                    b.ToTable("Agents");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.AuditLog", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Action").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("DateAction").HasColumnType("TEXT");
                    b.Property<string>("Details").HasColumnType("TEXT");
                    b.Property<string>("Entite").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("EntiteId").HasColumnType("TEXT");
                    b.Property<int?>("IdUtilisateur").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("IdUtilisateur");
                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Conge", b =>
                {
                    b.Property<int>("IdConge").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("DateDebut").HasColumnType("TEXT");
                    b.Property<DateTime>("DateFin").HasColumnType("TEXT");
                    b.Property<int>("Duree").HasColumnType("INTEGER");
                    b.Property<int>("IdDemande").HasColumnType("INTEGER");
                    b.Property<string>("Statut").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("TypeConge").HasColumnType("TEXT");
                    b.HasKey("IdConge");
                    b.HasIndex("IdDemande").IsUnique();
                    b.ToTable("Conges");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.DemandeConge", b =>
                {
                    b.Property<int>("IdDemande").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Commentaire").HasColumnType("TEXT");
                    b.Property<DateTime>("DateDemande").HasColumnType("TEXT");
                    b.Property<DateTime?>("DateDebut").HasColumnType("TEXT");
                    b.Property<DateTime?>("DateFin").HasColumnType("TEXT");
                    b.Property<int>("IdAgent").HasColumnType("INTEGER");
                    b.Property<string>("Statut").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("TypeConge").HasColumnType("TEXT");
                    b.HasKey("IdDemande");
                    b.HasIndex("IdAgent");
                    b.ToTable("DemandesConge");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.JournalConnexion", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("AdresseIp").HasColumnType("TEXT");
                    b.Property<DateTime>("DateConnexion").HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                    b.Property<int?>("IdUtilisateur").HasColumnType("INTEGER");
                    b.Property<string>("Message").HasColumnType("TEXT");
                    b.Property<bool>("Reussi").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("IdUtilisateur");
                    b.ToTable("JournauxConnexion");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Poste", b =>
                {
                    b.Property<int>("IdPoste").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Description").HasColumnType("TEXT");
                    b.Property<int>("IdService").HasColumnType("INTEGER");
                    b.Property<int>("NbPostes").HasColumnType("INTEGER");
                    b.Property<string>("NomPoste").IsRequired().HasColumnType("TEXT");
                    b.HasKey("IdPoste");
                    b.HasIndex("IdService");
                    b.ToTable("Postes");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Role", b =>
                {
                    b.Property<int>("IdRole").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Description").HasColumnType("TEXT");
                    b.Property<string>("NomRole").IsRequired().HasColumnType("TEXT");
                    b.HasKey("IdRole");
                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Service", b =>
                {
                    b.Property<int>("IdService").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Description").HasColumnType("TEXT");
                    b.Property<string>("NomService").IsRequired().HasColumnType("TEXT");
                    b.HasKey("IdService");
                    b.ToTable("Services");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime?>("DateBlocage").HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("EstActif").HasColumnType("INTEGER");
                    b.Property<int>("IdAgent").HasColumnType("INTEGER");
                    b.Property<int>("IdRole").HasColumnType("INTEGER");
                    b.Property<string>("MotPasse").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Nom").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime?>("ResetTokenExpiration").HasColumnType("TEXT");
                    b.Property<string>("ResetToken").HasColumnType("TEXT");
                    b.Property<int>("TentativesEchouees").HasColumnType("INTEGER");
                    b.HasKey("IdUtilisateur");
                    b.HasIndex("IdAgent").IsUnique();
                    b.HasIndex("IdRole");
                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Agent", b =>
                {
                    b.HasOne("GestionPersonnelMairie.Models.Poste", "Poste").WithMany("Agents").HasForeignKey("IdPoste").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("GestionPersonnelMairie.Models.Service", "Service").WithMany("Agents").HasForeignKey("IdService").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Poste");
                    b.Navigation("Service");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.AuditLog", b =>
                {
                    b.HasOne("GestionPersonnelMairie.Models.Utilisateur", "Utilisateur").WithMany().HasForeignKey("IdUtilisateur").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Conge", b =>
                {
                    b.HasOne("GestionPersonnelMairie.Models.DemandeConge", "DemandeConge").WithOne("Conge").HasForeignKey("GestionPersonnelMairie.Models.Conge", "IdDemande").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("DemandeConge");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.DemandeConge", b =>
                {
                    b.HasOne("GestionPersonnelMairie.Models.Agent", "Agent").WithMany("DemandesConge").HasForeignKey("IdAgent").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Agent");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.JournalConnexion", b =>
                {
                    b.HasOne("GestionPersonnelMairie.Models.Utilisateur", "Utilisateur").WithMany().HasForeignKey("IdUtilisateur").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Poste", b =>
                {
                    b.HasOne("GestionPersonnelMairie.Models.Service", "Service").WithMany("Postes").HasForeignKey("IdService").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Service");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Utilisateur", b =>
                {
                    b.HasOne("GestionPersonnelMairie.Models.Agent", "Agent").WithOne("Utilisateur").HasForeignKey("GestionPersonnelMairie.Models.Utilisateur", "IdAgent").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("GestionPersonnelMairie.Models.Role", "Role").WithMany("Utilisateurs").HasForeignKey("IdRole").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Agent");
                    b.Navigation("Role");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Agent", b =>
                {
                    b.Navigation("DemandesConge");
                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.DemandeConge", b =>
                {
                    b.Navigation("Conge");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Poste", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("GestionPersonnelMairie.Models.Service", b =>
                {
                    b.Navigation("Agents");
                    b.Navigation("Postes");
                });
#pragma warning restore 612, 618
        }
    }
}
